version: "3.9"

services:
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  # Map the host 'data' folder to the container '/app/data'
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
# version: "3.9"

# services:
#   app:
#     build:
#       context: .
#     container_name: fastapi_app
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./app/data:/app/data  # Mounts the data directory
#     environment:
#       - PYTHONUNBUFFERED=1
#     restart: always
