global:
  scrape_interval: 15s

# scrape_configs:
#   - job_name: "fastapi_app"
#     static_configs:
#       - targets: ["core_api:8000"]
scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["docker-fastapi-test:8000"]



  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
